### ISSUE TITLE
Go to target command not working

### ISSUE THREAD

**Issue by seppelicous** [BrokenThings/node-red-contrib-xiaomi-roborock#3]
Hi,
at first, thanks for the add-on!
I tried to send my rob to a specific coordinate, but the command to do that:
{
  "id": 25736111,
  "method": "app_goto_target",
  "params": [24200,20200]
}
let my Roborock respond "here I am". Thats it.
Does your code support the latest firmware and roborock commands?

best regards!

**Comment by KL-AU-S** [comment]
Hi, my app_goto_target is also not working. The only difference is, that in my case, simply nothing happend.
Kind regards
![roborock-goto](https://user-images.githubusercontent.com/42833559/51790034-63824600-2190-11e9-8fea-ca5e6447c188.png)

**Comment by BrokenThings** [comment]
Args for the app_goto_target command need to be passed as array. Example in #4

**Comment by KL-AU-S** [comment]
Thanks a lot, works fine. Kind regards Klaus

**Comment by MickL** [comment]
@KL-AU-S How did you do it exactly? I created a function and the request looks good, but still nothing happens:

<img width="686" alt="Bildschirmfoto 2019-07-05 um 15 34 16" src="https://user-images.githubusercontent.com/5103210/60725857-656be480-9f3a-11e9-93ec-b24a6f2a85c6.png">

<img width="492" alt="Bildschirmfoto 2019-07-05 um 15 33 04" src="https://user-images.githubusercontent.com/5103210/60725862-6ac92f00-9f3a-11e9-99ef-4c18cf888f44.png">

<img width="359" alt="Bildschirmfoto 2019-07-05 um 15 35 35" src="https://user-images.githubusercontent.com/5103210/60725917-8df3de80-9f3a-11e9-9977-4ac4cc718909.png">

In comparison: find_me is working
