### ISSUE TITLE
Zoned clean not working

### ISSUE THREAD

**Issue by KL-AU-S** [BrokenThings/node-red-contrib-xiaomi-roborock#4]
I´m trying to setup the zoned clean mode. The command is passed but nothing happend.
![roborock-zoned-clean](https://user-images.githubusercontent.com/42833559/51789881-1ef5ab00-218e-11e9-9532-f10a8763672b.png)

**Comment by baloonka** [comment]
![app_goto_target](https://user-images.githubusercontent.com/47757693/52973025-0a878580-33bd-11e9-8085-ea808db74301.PNG)
Hi, i have the same problem. Commands without args work well. Others with the argument do not work. Like app_goto_target. Where could be the problem?

**Comment by BrokenThings** [comment]
Hi,

in your cases the args are passed as string, but need to be passed as array.
Please try to pass a JSON payload like this to the node:
{"command":"app_zoned_clean","args":[[21500,23500,26000,25000,1]],"jobid":"103"}

This should result in the following request object:
![grafik](https://user-images.githubusercontent.com/40001953/53284810-7f5e1500-3759-11e9-9619-5b2948fae12c.png)

**Comment by KL-AU-S** [comment]
Thanks a lot, works fine. Kind regards Klaus
