### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Bundeshorst** [BrokenThings/node-red-contrib-xiaomi-roborock#5]
Node doesn't work for me. Seem's it ist broken. Debug shows only "undefined".
Token is correct. 
Roborock Firmware: 3.3.9_001720

<img width="823" alt="nodered-rockrobo" src="https://user-images.githubusercontent.com/16289714/56090029-5413be80-5e9c-11e9-8d38-868cbd543338.png">

**Comment by JaviElio** [comment]
Connection should be configured with the IP address (host) and token.

![DeepinScreenshot_20190424224403](https://user-images.githubusercontent.com/25644638/56692570-c6796f80-66e2-11e9-94c2-6fd9d8af9ae1.png)

Also change select "Complete msg Object" option in the debug node

**Comment by Bundeshorst** [comment]
Now it works - thank you!

**Comment by MickL** [comment]
@Bundeshorst You can close this issue if it works now
