### ISSUE TITLE
Dustbin info

### ISSUE THREAD

**Issue by JaviElio** [BrokenThings/node-red-contrib-xiaomi-roborock#7]
Is there any way to know if dustbin is full?

**Comment by MickL** [comment]
Checkout https://github.com/marcelrv/XiaomiRobotVacuumProtocol to see all available commands. I didnt try, but I assume you want to use `get_status` which has a `state` variable. The status `100` (Full) might mean that the dust bin is full. 

So you could frequently get the status, check if it is 100 and then do whatever you want to do.
