### ISSUE TITLE
"Known Issues" is not present on node-red page

### ISSUE THREAD

**Issue by MickL** [BrokenThings/node-red-contrib-xiaomi-roborock#8]
The readme of this repository contains an important "Known issues" information. Without this information a lot of commands will not work and the user don't know why. Unfortionally this is missing on the node red page:

https://flows.nodered.org/node/node-red-contrib-xiaomi-roborock

**Comment by BrokenThings** [comment]
bumped version to 0.0.2 to fix this - should be updated within the next hours
